blank_issues_enabled: false
contact_links:
  - name: Visit template-repo
    url: https://github.com/api7/template-repo
    about: Ask questions or discuss with other community members about template-repo
