blank_issues_enabled: false
contact_links:
  - name: Visit template-apache-repo
    url: https://github.com/api7/template-apache-repo
    about: Ask questions or discuss with other community members about template-apache-repo
